In [1]:
import torch

In [2]:
print(torch.__version__)

2.10.0+cpu


In [6]:
x=torch.tensor([[1,2,3,4,5],[1,2,3,4,5]])
print(x)

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])


In [10]:
import numpy as np
arr=np.array([1,2,3])
c=torch.from_numpy(arr)

In [11]:
c

tensor([1, 2, 3])

linear algebra

In [12]:
y=torch.tensor([2,4,6,8])
x=torch.tensor([1,2,3,4])
m=torch.tensor(0.0)
c=torch.tensor(0.0)

In [13]:
y_pre=m*x+c

In [15]:
loss=((y_pre-y)**2).mean()

In [16]:
print(y_pre)
print(y)
print(loss)

tensor([0., 0., 0., 0.])
tensor([2, 4, 6, 8])
tensor(30.)
