In [1]:
import torch

In [2]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [3]:
torch.rand(2,3)

tensor([[0.2999, 0.3144, 0.3486],
        [0.1454, 0.3343, 0.7470]])

In [4]:
torch.manual_seed(3)
torch.rand(3,2)

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270],
        [0.4716, 0.0601]])

In [5]:
torch.manual_seed(3)
torch.rand(3,2)

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270],
        [0.4716, 0.0601]])

In [6]:
torch.tensor([[1,2,3],[3,4,3]])

tensor([[1, 2, 3],
        [3, 4, 3]])

In [7]:
torch.range(0,10,2)

C:\Users\kumar\AppData\Local\Temp\ipykernel_26420\2765515675.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10,2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [8]:
x=torch.tensor([[1,2,3,4],[1,4,23,4]])

In [9]:
x.shape

torch.Size([2, 4])

In [10]:
torch.empty_like(x)

tensor([[5343174459712,             0,             0,             0],
        [            0,             0,             0,             0]])

In [11]:
torch.ones_like(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [12]:
torch.rand_like(x,dtype=torch.float)

tensor([[0.7719, 0.7437, 0.5944, 0.8879],
        [0.4510, 0.7995, 0.1498, 0.4015]])

In [13]:
x

tensor([[ 1,  2,  3,  4],
        [ 1,  4, 23,  4]])

In [14]:
(x*4)-3

tensor([[ 1,  5,  9, 13],
        [ 1, 13, 89, 13]])

In [15]:
torch.clamp(x,min=1,max=3)

tensor([[1, 2, 3, 3],
        [1, 3, 3, 3]])

In [16]:
torch.max(x,dim=1)

torch.return_types.max(
values=tensor([ 4, 23]),
indices=tensor([3, 2]))

In [17]:
torch.argmin(x)

tensor(0)

In [18]:
torch.cuda.is_available()

False

In [19]:
torch.rand(2,3)

tensor([[0.0542, 0.4594, 0.1756],
        [0.9492, 0.8473, 0.8749]])

In [20]:

import time

In [21]:
size=10000
m1=torch.rand(size,size)
m2=torch.rand(size,size)
start_time=time.time()
res=torch.matmul(m1,m2)
cpu_time=time.time()-start_time
print(cpu_time)


5.963943958282471


# auto grad

In [22]:
x=torch.tensor(4.0,requires_grad=True)


In [23]:
x

tensor(4., requires_grad=True)

In [24]:
y=x**2

In [25]:
y

tensor(16., grad_fn=<PowBackward0>)

In [26]:
#x.backward()

In [27]:
#x.grad

In [28]:
z=torch.sin(y)

In [29]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [30]:
z.backward()

In [31]:
x.grad

tensor(-7.6613)

In [32]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [33]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [34]:
z=w*x+b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [35]:
y_pre=torch.sigmoid(z)
y_pre

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [36]:
import math

In [37]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
y=(x**2).mean()

In [38]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [39]:
y.backward()

In [40]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

# clearing grad

In [41]:
x=torch.tensor(2.0,requires_grad=True)


In [42]:
y=x**2

In [43]:
y.backward()

In [44]:
x.grad

tensor(4.)

In [45]:
x.grad.zero_()

tensor(0.)

In [46]:
w=torch.tensor(0.0,requires_grad=True)
x=torch.tensor([1.,2.,3.,4.])
y_true=torch.tensor([2.,4.,6.,8.])
lr=0.1
epochs=10
for epoch in range(epochs):
    y_pre=w*x
    loss=((y_pre-y_true)**2).mean()
    loss.backward()
    with torch.no_grad():
        w-=lr*w.grad
    print(f"epoch{epoch+1}:w{w.item():.4f},loss={loss.item():.4f}")


epoch1:w3.0000,loss=30.0000
epoch2:w4.5000,loss=7.5000
epoch3:w2.2500,loss=46.8750
epoch4:w-0.3750,loss=0.4688
epoch5:w0.5625,loss=42.3047
epoch6:w3.6562,loss=15.4980
epoch7:w4.2656,loss=20.5737
epoch8:w1.4766,loss=38.4979
epoch9:w-0.5273,loss=2.0549
epoch10:w1.2598,loss=47.9060


# A simple project

In [ ]:
import torch 
import torch.nn as nn
import torch.optim as optim
from torchvision.datasets import MNIST
from torchvision import transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
device="cuda" if torch.cuda.is_available() else "cpu"
print("using device:",device)

transform=transforms.toTensor()

train_data=MNIST(
    root="data",
    train=True,
    download=True,
    transform=transform

)
test_data=MNIST(
    root="data",
    train=False,
    download=True,
    transform=transform

)
train_loader=DataLoader(train_data,batch_size=64,shuffle=True)
test_loader=DataLoader(test_data,batch_size=64,shuffle=False)
class DigitModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.net=nn.Sequential(nn.Linear(28*28,128),
            nn.ReLU(),
            nn.Linear(128,64),
            nn.ReLU(),
             nn.Linear(64,10)   )
    def forward(self,x):
        return self.net(x)
    

model=DigitModel().to(device)
loss_fn=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(),lr=0.001)

epochs=5
for epoch in range(epochs):
    images=images.view(images.size(0),-1).to(device)
    labels=labels.to(device)
    optimizer.zero_grad()
    outputs=model(images)
    loss=loss_fn(outputs,labels)
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()
+print(f"Epoch{epoch+1}/{epochs}|loss:{total_loss:.4f}")